// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { defineApp } from './core/defineApp';
export type { RuntimeConfig } from './core/defineApp';
export { createHistory, history } from './core/history';
export { terminal } from './core/terminal';
// @umijs/renderer-*
export {
  createBrowserHistory,
  createHashHistory,
  createMemoryHistory,
  createSearchParams,
  generatePath,
  Helmet,
  HelmetProvider,
  Link,
  matchPath,
  matchRoutes,
  Navigate,
  NavLink,
  Outlet,
  renderClient,
  resolvePath,
  useAppData,
  useClientLoaderData,
  useLocation,
  useMatch,
  useNavigate,
  useOutlet,
  useOutletContext,
  useParams,
  useResolvedPath,
  useRouteData,
  useRouteProps,
  useRoutes,
  useSearchParams,
  useSelectedRoutes,
  useServerLoaderData,
  withRouter,
  __getRoot,
  __useFetcher,
} from '/Users/congxiaochen/Documents/inula/node_modules/.pnpm/@umijs+renderer-react@4.0.88_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react';
export type { History } from '/Users/congxiaochen/Documents/inula/node_modules/.pnpm/@umijs+renderer-react@4.0.88_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react';
// umi/client/client/plugin
export {
  ApplyPluginsType,
  PluginManager,
} from '/Users/congxiaochen/Documents/inula/packages/inula/client/client/plugin.js';
export const useServerInsertedHTML: Function = () => {};
// plugins
// plugins types.d.ts
